
# for local development
version: '3.8'
services:
  quasar:
    build:
      context: .
      dockerfile: app.Dockerfile
      target: 'develop-stage'
    ports:
    - '9000:8080'
    volumes:
    - '.:/app'
    command: /bin/sh -c "quasar dev - --host"
