version: '3.8'

services:
  app:
    build:
      context: backend/
      dockerfile: app.Dockerfile
      args:
        - ENV=development
    entrypoint: [ /bin/sh, -c, "flask db upgrade && python -m debugpy --listen 0.0.0.0:5678  /app/manage.py --app src run --host 0.0.0.0"]
    env_file:
      - backend/.env

    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
      - '5678:5678'
  quasar:
    build:
      context: frontend/
      dockerfile: app.Dockerfile
      target: 'develop-stage'
    ports:
    - '9000:9000'
    volumes:
    - './frontend:/app'
    command: /bin/sh -c "npm install && quasar dev --hostname 0.0.0.0 --port 9000"