name: Build and Deploy
on:
  push:
    branches:
      - main
      - deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/checkout@v2
      - name: build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/uffride:latest -f deploy.Dockerfile .

      - name: push docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/uffride:latest

      - name: Deploy on Cloud Run
        uses: GoogleCloudPlatform/github-actions/cloud-run@main
        with:
          service: sandbox-uffride
          image: ${{ secrets.DOCKER_USERNAME }}/uffride:latest
          project_id: ${{ secrets.PROJECT_ID }}
          region: us-central1
          platform: managed
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          revision_suffix: ${{ github.sha }}
          allow_unauthenticated: true