name: Build and Deploy
on:
  push:
    branches:
      - main
      - deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/checkout@v2
      - name: build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/uffride:latest -f deploy.Dockerfile .

      - name: push docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/uffride:latest

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true
    
      - name: Deploy to Cloud Run
        run: gcloud run deploy sandbox-uffride --image ${{ secrets.DOCKER_USERNAME }}/uffride:latest --platform managed --region us-central1 --allow-unauthenticated --revision-suffix ${{ github.sha }}