name: Pipeline Pull Request
on:
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/checkout@v2
      - name: build docker image
        run: |  
          cd backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/uffride:${{ github.sha }} -f app.Dockerfile .
          docker run --rm -v $(pwd):/app -w /app  ${{ secrets.DOCKER_USERNAME }}/uffride:${{ github.sha }} --entrypoint "pytest tests/*"